# ESP8266 Dog Water Bowl Sensor
#
substitutions:
  devicename: dog_water
  devicename_upper: Dog Water Bowl

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable Home Assistant API
api:

ota:
  safe_mode: True

# Enable logging
logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      #mode: INPUT_PULLUP
      inverted: True
    name: ${devicename_upper}
    device_class: moisture
    filters:
      - delayed_on: 20ms
    
sensor:
  - platform: wifi_signal
    name: ${devicename}_wifi_signal
    update_interval: 30s
    
  - platform: uptime
    name: ${devicename}_uptime

text_sensor:
  - platform: version
    name: ${devicename}_esphome_version