---
# Sonoff Power Module
#
substitutions:
  project: Sonoff POW 02
  id: sonoff_pow_02

  <<: !include common/substitutions/gpio/sonoffpow.yaml

<<: !include common/templates/sonoff_pow.yaml
