---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  project: Sonoff S31 04
  id: sonoff_s31_04

  <<: !include common/substitutions/gpio/sonoffs31.yaml

<<: !include common/templates/sonoff_s31.yaml
