---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  project: Sonoff S31 01
  id: sonoff_s31_01

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
